server:
  port: 8888

          #username:
          #password:


#        native:
#          search-locations: file:C:/Users/alstn/Desktop/springStudy/git-local-repo




management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, bursefresh

  endpoint:
    shutdown:
      enabled: true
spring:
  rabbitmq:
    host: 127.0.0.1
    password: guest1234
    username: user